### ISSUE TITLE
have problem when run 'python setup.py install --user'

### ISSUE THREAD

**Issue by ShuhangGe** [Pang-Yatian/Point-MAE#30]
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-11.7'
running install
/home/shuhang/install/anaconda3/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/home/shuhang/install/anaconda3/lib/python3.10/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
writing chamfer.egg-info/PKG-INFO
writing dependency_links to chamfer.egg-info/dependency_links.txt
writing top-level names to chamfer.egg-info/top_level.txt
/home/shuhang/install/anaconda3/lib/python3.10/site-packages/torch/utils/cpp_extension.py:413: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
reading manifest file 'chamfer.egg-info/SOURCES.txt'
writing manifest file 'chamfer.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
Traceback (most recent call last):
  File "/media/shuhang/04C405E5C405D9B6/paper_code/point_mae/Point-MAE-main/extensions/chamfer_dist/setup.py", line 11, in <module>
    setup(name='chamfer',
  File "/home/shuhang/install/anaconda3/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/shuhang/install/anaconda3/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/shuhang/install/anaconda3/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/shuhang/install/anaconda3/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/shuhang/install/anaconda3/lib/python3.10/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/home/shuhang/install/anaconda3/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/shuhang/install/anaconda3/lib/python3.10/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/home/shuhang/install/anaconda3/lib/python3.10/site-packages/setuptools/command/install.py", line 123, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/shuhang/install/anaconda3/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/shuhang/install/anaconda3/lib/python3.10/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/home/shuhang/install/anaconda3/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/shuhang/install/anaconda3/lib/python3.10/site-packages/setuptools/command/bdist_egg.py", line 165, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/shuhang/install/anaconda3/lib/python3.10/site-packages/setuptools/command/bdist_egg.py", line 151, in call_command
    self.run_command(cmdname)
  File "/home/shuhang/install/anaconda3/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/shuhang/install/anaconda3/lib/python3.10/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/home/shuhang/install/anaconda3/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/shuhang/install/anaconda3/lib/python3.10/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/shuhang/install/anaconda3/lib/python3.10/site-packages/setuptools/_distutils/command/install_lib.py", line 112, in build
    self.run_command('build_ext')
  File "/home/shuhang/install/anaconda3/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/shuhang/install/anaconda3/lib/python3.10/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/home/shuhang/install/anaconda3/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/shuhang/install/anaconda3/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/home/shuhang/install/anaconda3/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
    self.build_extensions()
  File "/home/shuhang/install/anaconda3/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 436, in build_extensions
    self._check_cuda_version(compiler_name, compiler_version)
  File "/home/shuhang/install/anaconda3/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 813, in _check_cuda_version
    torch_cuda_version = packaging.version.parse(torch.version.cuda)
  File "/home/shuhang/install/anaconda3/lib/python3.10/site-packages/pkg_resources/_vendor/packaging/version.py", line 49, in parse
    return Version(version)
  File "/home/shuhang/install/anaconda3/lib/python3.10/site-packages/pkg_resources/_vendor/packaging/version.py", line 265, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object

I meet this problem when I tried to install chamfer, I stucked by this problem for a long time, can you give me some help? Thank you.

**Comment by Pari0511** [comment]
> No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-11.7' running install /home/shuhang/install/anaconda3/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools. warnings.warn( /home/shuhang/install/anaconda3/lib/python3.10/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools. warnings.warn( running bdist_egg running egg_info writing chamfer.egg-info/PKG-INFO writing dependency_links to chamfer.egg-info/dependency_links.txt writing top-level names to chamfer.egg-info/top_level.txt /home/shuhang/install/anaconda3/lib/python3.10/site-packages/torch/utils/cpp_extension.py:413: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend. warnings.warn(msg.format('we could not find ninja.')) reading manifest file 'chamfer.egg-info/SOURCES.txt' writing manifest file 'chamfer.egg-info/SOURCES.txt' installing library code to build/bdist.linux-x86_64/egg running install_lib running build_ext Traceback (most recent call last): File "/media/shuhang/04C405E5C405D9B6/paper_code/point_mae/Point-MAE-main/extensions/chamfer_dist/setup.py", line 11, in setup(name='chamfer', File "/home/shuhang/install/anaconda3/lib/python3.10/site-packages/setuptools/**init**.py", line 87, in setup return distutils.core.setup(**attrs) File "/home/shuhang/install/anaconda3/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup return run_commands(dist) File "/home/shuhang/install/anaconda3/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands dist.run_commands() File "/home/shuhang/install/anaconda3/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands self.run_command(cmd) File "/home/shuhang/install/anaconda3/lib/python3.10/site-packages/setuptools/dist.py", line 1208, in run_command super().run_command(command) File "/home/shuhang/install/anaconda3/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command cmd_obj.run() File "/home/shuhang/install/anaconda3/lib/python3.10/site-packages/setuptools/command/install.py", line 74, in run self.do_egg_install() File "/home/shuhang/install/anaconda3/lib/python3.10/site-packages/setuptools/command/install.py", line 123, in do_egg_install self.run_command('bdist_egg') File "/home/shuhang/install/anaconda3/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command self.distribution.run_command(command) File "/home/shuhang/install/anaconda3/lib/python3.10/site-packages/setuptools/dist.py", line 1208, in run_command super().run_command(command) File "/home/shuhang/install/anaconda3/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command cmd_obj.run() File "/home/shuhang/install/anaconda3/lib/python3.10/site-packages/setuptools/command/bdist_egg.py", line 165, in run cmd = self.call_command('install_lib', warn_dir=0) File "/home/shuhang/install/anaconda3/lib/python3.10/site-packages/setuptools/command/bdist_egg.py", line 151, in call_command self.run_command(cmdname) File "/home/shuhang/install/anaconda3/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command self.distribution.run_command(command) File "/home/shuhang/install/anaconda3/lib/python3.10/site-packages/setuptools/dist.py", line 1208, in run_command super().run_command(command) File "/home/shuhang/install/anaconda3/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command cmd_obj.run() File "/home/shuhang/install/anaconda3/lib/python3.10/site-packages/setuptools/command/install_lib.py", line 11, in run self.build() File "/home/shuhang/install/anaconda3/lib/python3.10/site-packages/setuptools/_distutils/command/install_lib.py", line 112, in build self.run_command('build_ext') File "/home/shuhang/install/anaconda3/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command self.distribution.run_command(command) File "/home/shuhang/install/anaconda3/lib/python3.10/site-packages/setuptools/dist.py", line 1208, in run_command super().run_command(command) File "/home/shuhang/install/anaconda3/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command cmd_obj.run() File "/home/shuhang/install/anaconda3/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 84, in run _build_ext.run(self) File "/home/shuhang/install/anaconda3/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run self.build_extensions() File "/home/shuhang/install/anaconda3/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 436, in build_extensions self._check_cuda_version(compiler_name, compiler_version) File "/home/shuhang/install/anaconda3/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 813, in _check_cuda_version torch_cuda_version = packaging.version.parse(torch.version.cuda) File "/home/shuhang/install/anaconda3/lib/python3.10/site-packages/pkg_resources/_vendor/packaging/version.py", line 49, in parse return Version(version) File "/home/shuhang/install/anaconda3/lib/python3.10/site-packages/pkg_resources/_vendor/packaging/version.py", line 265, in **init** match = self._regex.search(version) TypeError: expected string or bytes-like object
> 
> I meet this problem when I tried to install chamfer, I stucked by this problem for a long time, can you give me some help? Thank you.

Are you using any env to run this code. First do on base env only. And before running the "setup.py install" command do:

module av  (to check is your cud is there in root)
module spider cuda                               //  show all cuda versions you have
module load cuda/11.1.1                      // in my case its 11.1.1    
which nvcc                                             // show cuda_home path, we use output of this in next command
CUDA_HOME=/opt/apps/cuda/11.1.1   // in my case  
echo $CUDA_HOME
python3 setup.py install --user             // will run properly without CUDA_HOME error.

hope it helps you ,thank you.
