### ISSUE TITLE
chamfer_dist compile for sm_90 GPU architecture

### ISSUE THREAD

**Issue by saimunur** [Pang-Yatian/Point-MAE#47]
Hi! I am facing the following error while compiling chamfer_dist for sm_90 GPU architecture (with CUDA 12.1):

```
Processing ./Point-MAE/extensions/chamfer_dist
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: chamfer
  Building wheel for chamfer (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [90 lines of output]
      running bdist_wheel
      running build
      running build_ext
      /pointmae/env/lib/python3.10/site-packages/torch/utils/cpp_extension.py:424: UserWarning: There are no g++ version bounds defined for CUDA version 12.1
        warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')
      building 'chamfer' extension
      creating /pointmae/Point-MAE/extensions/chamfer_dist/build
      creating /pointmae/Point-MAE/extensions/chamfer_dist/build/temp.linux-x86_64-cpython-310
      Emitting ninja build file /pointmae/Point-MAE/extensions/chamfer_dist/build/temp.linux-x86_64-cpython-310/build.ninja...
      Compiling objects...
      Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
      [1/2] g++ -MMD -MF /pointmae/Point-MAE/extensions/chamfer_dist/build/temp.linux-x86_64-cpython-310/chamfer_cuda.o.d -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /pointmae/env/include -fPIC -O2 -isystem /pointmae/env/include -fPIC -I/pointmae/env/lib/python3.10/site-packages/torch/include -I/pointmae/env/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/pointmae/env/lib/python3.10/site-packages/torch/include/TH -I/pointmae/env/lib/python3.10/site-packages/torch/include/THC -I/apps/cuda/12.1.0/include -I/pointmae/env/include/python3.10 -c -c /pointmae/Point-MAE/extensions/chamfer_dist/chamfer_cuda.cpp -o /pointmae/Point-MAE/extensions/chamfer_dist/build/temp.linux-x86_64-cpython-310/chamfer_cuda.o -O2 -std=c++17 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=chamfer -D_GLIBCXX_USE_CXX11_ABI=0
      [2/2] /apps/cuda/12.1.0/bin/nvcc  -I/pointmae/env/lib/python3.10/site-packages/torch/include -I/pointmae/env/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/pointmae/env/lib/python3.10/site-packages/torch/include/TH -I/pointmae/env/lib/python3.10/site-packages/torch/include/THC -I/apps/cuda/12.1.0/include -I/pointmae/env/include/python3.10 -c -c /pointmae/Point-MAE/extensions/chamfer_dist/chamfer.cu -o /pointmae/Point-MAE/extensions/chamfer_dist/build/temp.linux-x86_64-cpython-310/chamfer.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O2 -std=c++17 --expt-relaxed-constexpr -gencode=arch=compute_90,code=compute_90 -gencode=arch=compute_90,code=sm_90 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=chamfer -D_GLIBCXX_USE_CXX11_ABI=0 -ccbin gcc
      FAILED: /pointmae/Point-MAE/extensions/chamfer_dist/build/temp.linux-x86_64-cpython-310/chamfer.o
      /apps/cuda/12.1.0/bin/nvcc  -I/pointmae/env/lib/python3.10/site-packages/torch/include -I/pointmae/env/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/pointmae/env/lib/python3.10/site-packages/torch/include/TH -I/pointmae/env/lib/python3.10/site-packages/torch/include/THC -I/apps/cuda/12.1.0/include -I/pointmae/env/include/python3.10 -c -c /pointmae/Point-MAE/extensions/chamfer_dist/chamfer.cu -o /pointmae/Point-MAE/extensions/chamfer_dist/build/temp.linux-x86_64-cpython-310/chamfer.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O2 -std=c++17 --expt-relaxed-constexpr -gencode=arch=compute_90,code=compute_90 -gencode=arch=compute_90,code=sm_90 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=chamfer -D_GLIBCXX_USE_CXX11_ABI=0 -ccbin gcc
      /pointmae/env/lib/python3.10/site-packages/torch/include/pybind11/detail/../cast.h: In function ‘typename pybind11::detail::type_caster<typename pybind11::detail::intrinsic_type<T>::type>::cast_op_type<T> pybind11::detail::cast_op(make_caster<T>&)’:
      /pointmae/env/lib/python3.10/site-packages/torch/include/pybind11/detail/../cast.h:45:120: error: expected template-name before ‘<’ token
         45 |     return caster.operator typename make_caster<T>::template cast_op_type<T>();
            |                                                                                                                        ^
      /pointmae/env/lib/python3.10/site-packages/torch/include/pybind11/detail/../cast.h:45:120: error: expected identifier before ‘<’ token
      /pointmae/env/lib/python3.10/site-packages/torch/include/pybind11/detail/../cast.h:45:123: error: expected primary-expression before ‘>’ token
         45 |     return caster.operator typename make_caster<T>::template cast_op_type<T>();
            |                                                                                                                           ^
      /pointmae/env/lib/python3.10/site-packages/torch/include/pybind11/detail/../cast.h:45:126: error: expected primary-expression before ‘)’ token
         45 |     return caster.operator typename make_caster<T>::template cast_op_type<T>();
            |                                                                                                                              ^
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/pointmae/env/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2100, in _run_ninja_build
          subprocess.run(
        File "/pointmae/env/lib/python3.10/subprocess.py", line 526, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/pointmae/Point-MAE/extensions/chamfer_dist/setup.py", line 25, in <module>
          setup(
        File "/pointmae/env/lib/python3.10/site-packages/setuptools/__init__.py", line 104, in setup
          return distutils.core.setup(**attrs)
        File "/pointmae/env/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
        File "/pointmae/env/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/pointmae/env/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/pointmae/env/lib/python3.10/site-packages/setuptools/dist.py", line 967, in run_command
          super().run_command(command)
        File "/pointmae/env/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/pointmae/env/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "/pointmae/env/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/pointmae/env/lib/python3.10/site-packages/setuptools/dist.py", line 967, in run_command
          super().run_command(command)
        File "/pointmae/env/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/pointmae/env/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/pointmae/env/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/pointmae/env/lib/python3.10/site-packages/setuptools/dist.py", line 967, in run_command
          super().run_command(command)
        File "/pointmae/env/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/pointmae/env/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 91, in run
          _build_ext.run(self)
        File "/pointmae/env/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
          self.build_extensions()
        File "/pointmae/env/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 873, in build_extensions
          build_ext.build_extensions(self)
        File "/pointmae/env/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 479, in build_extensions
          self._build_extensions_serial()
        File "/pointmae/env/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 505, in _build_extensions_serial
          self.build_extension(ext)
        File "/pointmae/env/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 252, in build_extension
          _build_ext.build_extension(self, ext)
        File "/pointmae/env/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 560, in build_extension
          objects = self.compiler.compile(
        File "/pointmae/env/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 686, in unix_wrap_ninja_compile
          _write_ninja_file_and_compile_objects(
        File "/pointmae/env/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1774, in _write_ninja_file_and_compile_objects
          _run_ninja_build(
        File "/pointmae/env/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2116, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for chamfer
  Running setup.py clean for chamfer
Failed to build chamfer
ERROR: Could not build wheels for chamfer, which is required to install pyproject.toml-based projects
```

It would be great if you could provide some guidance. In a bit of an urgent need. Thanks very much.

**Comment by Pang-Yatian** [comment]
Hi, 

I am sorry. We are not the author of this extension. It was borrowed from Point-BERT directly. I think you may replace it with some Pytorch implementations such as https://github.com/krrish94/chamferdist.
