### ISSUE TITLE
Bugs in modelnet40_8k pretrain model

### ISSUE THREAD

**Issue by cuge1995** [Pang-Yatian/Point-MAE#7]
```
PytorchStreamReader failed reading file data/399: invalid header or archive is corrupted
```

**Comment by Pang-Yatian** [comment]
Please provide full log and descriptions.

**Comment by cuge1995** [comment]
```
2022-04-12 19:22:25,191 - ModelNet - INFO - Load processed data from data/ModelNet/modelnet40_normal_resampled/modelnet40_test_8192pts_fps.dat...
2022-04-12 19:22:25,623 - finetune_modelnet_8k - INFO - Loading weights from modelnet_8k.pth...
Traceback (most recent call last):
  File "main.py", line 92, in <module>
    main()
  File "main.py", line 83, in main
    test_net(args, config)
  File "Point-MAE/tools/runner_finetune.py", line 361, in test_net
    builder.load_model(base_model, args.ckpts, logger = logger) # for finetuned transformer
  File "Point-MAE/tools/builder.py", line 144, in load_model
    state_dict = torch.load(ckpt_path, map_location='cpu')
  File "python3.6/site-packages/torch/serialization.py", line 594, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "python3.6/site-packages/torch/serialization.py", line 853, in _load
    result = unpickler.load()
  File "python3.6/site-packages/torch/serialization.py", line 845, in persistent_load
    load_tensor(data_type, size, key, _maybe_decode_ascii(location))
  File "python3.6/site-packages/torch/serialization.py", line 833, in load_tensor
    storage = zip_file.get_storage_from_record(name, size, dtype).storage()
RuntimeError: [enforce fail at inline_container.cc:145] . PytorchStreamReader failed reading file data/399: invalid header or archive is corrupted
```

**Comment by Pang-Yatian** [comment]
Are you using python 3.6?

**Comment by Pang-Yatian** [comment]
Are you using python 3.6? Please follow our requirements in Readme and have a try.

**Comment by cuge1995** [comment]
The model_1k.pth is ok, it's very strange.

**Comment by Pang-Yatian** [comment]
Yes, we did not meet this issue and there is very limited information about this bug.  We will reupload the ckpt.

```
2022-02-22 20:31:20,920 - F_e300_8k - INFO - Loading weights from experiments/F_e300_8k/ab/0.6R_8k_p1k/ckpt-best.pth...
2022-02-22 20:31:45,365 - F_e300_8k - INFO - ckpts @ 228 epoch( performance = {'acc': tensor(93.3955)})
```

**Comment by Pang-Yatian** [comment]
Hi, 

We download the older one ckpt and test and find the same issue. Now we have reuploaded the ckpt and test again. It should be OK this time.

```
2022-04-12 21:23:31,166 - finetune_modelnet_8k - INFO - Loading weights from modelnet_8k.pth...
2022-04-12 21:23:31,254 - finetune_modelnet_8k - INFO - ckpts @ 228 epoch( performance = {'acc': tensor(93.3955)})

```

Thanks a lot for pointing out this bug.
